-- ============================================================
-- 016 — Novo sistema de avisos (genérico, padronizado)
--
-- Substitui o modelo antigo (FRM_AVISO_SALA + FRM_AVISO_SALA_CIENCIA,
-- 1 mensagem por sala, exclusivo de operador) por um modelo único capaz
-- de comportar todos os tipos de aviso (VERIFICACAO, ESCALA, PESSOAL,
-- AGENDA, GERAL) e todos os públicos (operadores, técnicos, coletivos).
--
-- 4 tabelas:
--   FRM_AVISO_CADASTRO  — cabeçalho (tipo, regras, datas, autor, status)
--   FRM_AVISO_MENSAGEM  — 1..10 mensagens por cadastro
--   FRM_AVISO_ALVO      — público (sala / operador / técnico / coletivos)
--   FRM_AVISO_CIENCIA   — quem leu (operador OU técnico)
--
-- Não há migração de dados: o único registro existente é um teste
-- descartável. As tabelas antigas são dropadas.
-- ============================================================

-- ── Drop do modelo antigo (filho primeiro) ──
DROP TABLE FRM_AVISO_SALA_CIENCIA CASCADE CONSTRAINTS;
DROP TABLE FRM_AVISO_SALA CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_FRM_AVISO_SALA;


-- ── Sequence do número humano (Cadastro nº) ──
CREATE SEQUENCE SEQ_FRM_AVISO_CADASTRO START WITH 1 INCREMENT BY 1 NOCACHE;


-- ── FRM_AVISO_CADASTRO ──
CREATE TABLE FRM_AVISO_CADASTRO (
    ID                   VARCHAR2(36)  PRIMARY KEY,
    NUMERO               NUMBER(10)    NOT NULL,
    TIPO                 VARCHAR2(30)  NOT NULL,
    PERMANENTE           NUMBER(1)     DEFAULT 1 NOT NULL,
    DURACAO_DIAS         NUMBER(3),
    MANTER_APOS_CIENCIA  NUMBER(1)     DEFAULT 0 NOT NULL,
    STATUS               VARCHAR2(20)  DEFAULT 'Ativo' NOT NULL,
    CRIADO_POR_ID        VARCHAR2(36)  NOT NULL,
    CRIADO_EM            TIMESTAMP     NOT NULL,
    ATUALIZADO_EM        TIMESTAMP     NOT NULL,
    EXPIRA_EM            TIMESTAMP,
    DESATIVADO_EM        TIMESTAMP,
    CONSTRAINT UK_FRM_AVISO_CAD_NUMERO UNIQUE (NUMERO),
    CONSTRAINT CK_FRM_AVISO_CAD_TIPO CHECK (TIPO IN ('VERIFICACAO','ESCALA','PESSOAL','AGENDA','GERAL')),
    CONSTRAINT CK_FRM_AVISO_CAD_PERM CHECK (PERMANENTE IN (0,1)),
    CONSTRAINT CK_FRM_AVISO_CAD_MANTER CHECK (MANTER_APOS_CIENCIA IN (0,1)),
    CONSTRAINT CK_FRM_AVISO_CAD_STATUS CHECK (STATUS IN ('Ativo','Expirado','Desativado')),
    CONSTRAINT CK_FRM_AVISO_CAD_DURACAO CHECK (
        (PERMANENTE = 1 AND DURACAO_DIAS IS NULL)
        OR (PERMANENTE = 0 AND DURACAO_DIAS IS NOT NULL AND DURACAO_DIAS BETWEEN 1 AND 30)
    ),
    CONSTRAINT CK_FRM_AVISO_CAD_EXPIRA CHECK (
        (PERMANENTE = 1 AND EXPIRA_EM IS NULL)
        OR (PERMANENTE = 0 AND EXPIRA_EM IS NOT NULL)
    ),
    CONSTRAINT FK_FRM_AVISO_CAD_ADMIN FOREIGN KEY (CRIADO_POR_ID) REFERENCES PES_ADMINISTRADOR(ID)
);

CREATE INDEX IDX_FRM_AVISO_CAD_TIPO ON FRM_AVISO_CADASTRO (TIPO, STATUS);
CREATE INDEX IDX_FRM_AVISO_CAD_CRIADO ON FRM_AVISO_CADASTRO (CRIADO_EM);
CREATE INDEX IDX_FRM_AVISO_CAD_EXPIRA ON FRM_AVISO_CADASTRO (EXPIRA_EM);


-- ── FRM_AVISO_MENSAGEM ──
CREATE TABLE FRM_AVISO_MENSAGEM (
    ID             VARCHAR2(36)  PRIMARY KEY,
    CADASTRO_ID    VARCHAR2(36)  NOT NULL,
    ORDEM          NUMBER(2)     NOT NULL,
    TEXTO          CLOB          NOT NULL,
    CRIADO_EM      TIMESTAMP     NOT NULL,
    ATUALIZADO_EM  TIMESTAMP     NOT NULL,
    CONSTRAINT UK_FRM_AVISO_MSG_ORDEM UNIQUE (CADASTRO_ID, ORDEM),
    CONSTRAINT CK_FRM_AVISO_MSG_ORDEM CHECK (ORDEM BETWEEN 1 AND 10),
    CONSTRAINT FK_FRM_AVISO_MSG_CAD FOREIGN KEY (CADASTRO_ID) REFERENCES FRM_AVISO_CADASTRO(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_FRM_AVISO_MSG_CAD ON FRM_AVISO_MENSAGEM (CADASTRO_ID);


-- ── FRM_AVISO_ALVO ──
CREATE TABLE FRM_AVISO_ALVO (
    ID             VARCHAR2(36)  PRIMARY KEY,
    CADASTRO_ID    VARCHAR2(36)  NOT NULL,
    ALVO_TIPO      VARCHAR2(20)  NOT NULL,
    SALA_ID        NUMBER(5),
    OPERADOR_ID    VARCHAR2(36),
    TECNICO_ID     VARCHAR2(36),
    CRIADO_EM      TIMESTAMP     NOT NULL,
    ATUALIZADO_EM  TIMESTAMP     NOT NULL,
    CONSTRAINT CK_FRM_AVISO_ALVO_TIPO CHECK (ALVO_TIPO IN ('SALA','OPERADOR','TECNICO','TODOS_OPERADORES','TODOS_TECNICOS','TODOS')),
    CONSTRAINT CK_FRM_AVISO_ALVO_REF CHECK (
        (ALVO_TIPO = 'SALA'     AND SALA_ID     IS NOT NULL AND OPERADOR_ID IS NULL AND TECNICO_ID IS NULL)
        OR (ALVO_TIPO = 'OPERADOR' AND OPERADOR_ID IS NOT NULL AND SALA_ID     IS NULL AND TECNICO_ID IS NULL)
        OR (ALVO_TIPO = 'TECNICO'  AND TECNICO_ID  IS NOT NULL AND SALA_ID     IS NULL AND OPERADOR_ID IS NULL)
        OR (ALVO_TIPO IN ('TODOS_OPERADORES','TODOS_TECNICOS','TODOS') AND SALA_ID IS NULL AND OPERADOR_ID IS NULL AND TECNICO_ID IS NULL)
    ),
    CONSTRAINT FK_FRM_AVISO_ALVO_CAD FOREIGN KEY (CADASTRO_ID) REFERENCES FRM_AVISO_CADASTRO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_FRM_AVISO_ALVO_SALA FOREIGN KEY (SALA_ID) REFERENCES CAD_SALA(ID),
    CONSTRAINT FK_FRM_AVISO_ALVO_OPER FOREIGN KEY (OPERADOR_ID) REFERENCES PES_OPERADOR(ID),
    CONSTRAINT FK_FRM_AVISO_ALVO_TEC FOREIGN KEY (TECNICO_ID) REFERENCES PES_TECNICO(ID)
);

CREATE INDEX IDX_FRM_AVISO_ALVO_CAD ON FRM_AVISO_ALVO (CADASTRO_ID);
CREATE INDEX IDX_FRM_AVISO_ALVO_SALA ON FRM_AVISO_ALVO (SALA_ID);
CREATE INDEX IDX_FRM_AVISO_ALVO_OPER ON FRM_AVISO_ALVO (OPERADOR_ID);
CREATE INDEX IDX_FRM_AVISO_ALVO_TEC ON FRM_AVISO_ALVO (TECNICO_ID);


-- ── FRM_AVISO_CIENCIA ──
CREATE TABLE FRM_AVISO_CIENCIA (
    ID             VARCHAR2(36)  PRIMARY KEY,
    CADASTRO_ID    VARCHAR2(36)  NOT NULL,
    OPERADOR_ID    VARCHAR2(36),
    TECNICO_ID     VARCHAR2(36),
    CIENTE_EM      TIMESTAMP     NOT NULL,
    CRIADO_EM      TIMESTAMP     NOT NULL,
    ATUALIZADO_EM  TIMESTAMP     NOT NULL,
    CONSTRAINT CK_FRM_AVISO_CIE_PESSOA CHECK (
        (OPERADOR_ID IS NOT NULL AND TECNICO_ID IS NULL)
        OR (OPERADOR_ID IS NULL AND TECNICO_ID IS NOT NULL)
    ),
    CONSTRAINT FK_FRM_AVISO_CIE_CAD FOREIGN KEY (CADASTRO_ID) REFERENCES FRM_AVISO_CADASTRO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_FRM_AVISO_CIE_OPER FOREIGN KEY (OPERADOR_ID) REFERENCES PES_OPERADOR(ID),
    CONSTRAINT FK_FRM_AVISO_CIE_TEC FOREIGN KEY (TECNICO_ID) REFERENCES PES_TECNICO(ID)
);

-- Regra "só a 1ª ciência conta": índices únicos parciais por papel.
-- Linhas do outro papel recebem NULL na função e não disputam unicidade.
CREATE UNIQUE INDEX UK_FRM_AVISO_CIE_OP
    ON FRM_AVISO_CIENCIA (CASE WHEN OPERADOR_ID IS NOT NULL THEN CADASTRO_ID || '|' || OPERADOR_ID END);
CREATE UNIQUE INDEX UK_FRM_AVISO_CIE_TEC
    ON FRM_AVISO_CIENCIA (CASE WHEN TECNICO_ID IS NOT NULL THEN CADASTRO_ID || '|' || TECNICO_ID END);

CREATE INDEX IDX_FRM_AVISO_CIE_CAD ON FRM_AVISO_CIENCIA (CADASTRO_ID);
CREATE INDEX IDX_FRM_AVISO_CIE_OPER ON FRM_AVISO_CIENCIA (OPERADOR_ID);
CREATE INDEX IDX_FRM_AVISO_CIE_TEC ON FRM_AVISO_CIENCIA (TECNICO_ID);
